In [1]:
import numpy as np

In [7]:
a = np.array([1, 2, 3, 3, 1, 6, 8, 11, 10, 7]).reshape(2, 5).transpose()

In [8]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [11]:
mean_a = a.mean(axis=0)

In [12]:
mean_a

array([2. , 8.4])

In [14]:
a_centered = a - mean_a

In [15]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [20]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

In [21]:
a_centered_sp

8.0

In [23]:
N = a.shape[0]

In [24]:
a_centered_sp / (N - 1)

2.0

In [26]:
c = np.cov(a.transpose())

In [27]:
c[0, 1]

2.0